[tool.poetry]
name = "test_python"
version = "0.1.0"
description = ""
authors = ["ucpr <contact@ucpr.dev>"]

[tool.poetry.dependencies]
python = "^3.8"
pika = "^1.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
