name: docker_volume_test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
#    container:
#      image: zenika/alpine-chrome
#      options: -v /home/runner/work/workspace2020/workspace2020:/usr/src/app --no-sandbox --screenshot --hide-scrollbars https://www.chromestatus.com/

    steps:
      - name: take a pic
        uses: docker://zenika/alpine-chrome
        with:
          args: -v $(pwd):/usr/src/app zenika/alpine-chrome --no-sandbox --screenshot=hoge.png --hide-scrollbars https://www.chromestatus.com/

      - name: test
        run: |
          ls
          pwd
