name: docker_volume_test

on: push
#  issues:
#    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    container: cypress/browsers:node12.13.0-chrome78-ff70

    steps:
      - uses: actions/checkout@v2

      - name: tale a pic
        run: |
          google-chrome-stable --headless --disable-gpu --no-sandbox --screenshot https://www.chromestatus.com/
#      - name: take a pic
#        uses: docker://zenika/alpine-chrome
#        with:
#          entrypoint: chromium-browser --headless --disable-gpu --disable-software-rasterizer --disable-dev-shm-usage
#          args: -v $(pwd):/usr/src/app --no-sandbox --print-to-pdf=hoge.pdf --hide-scrollbars https://www.chromestatus.com/
#      - name: take a pic
#        run: |
#          docker container run -it --rm -v $(pwd):/usr/src/app zenika/alpine-chrome --no-sandbox --screenshot --hide-scrollbars https://www.chromestatus.com/
      - name: test
        run: |
          ls
          pwd
          echo 1

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - run: gcloud info
      - run: gsutil version
      
      - uses: actions/github-script@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: 1,
              owner: "ucpr",
              repo: "workspace2020",
              body: "👋 Thanks for reporting!\n ![test image](./screenshot.png)"
            }) 
  
